version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart:
      on-failure
    ports:
      - 8081:80

  backend:
    container_name: backend
    build: ./backend
    networks:
      - api-db
    env_file:
      - ./.env
    restart:
      on-failure
    ports:
      - 4000:3000
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:12
    networks:
      - api-db
    env_file:
      - ./.env
    restart:
      on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

volumes:
  pg_data:

networks:
  db: {}